### ISSUE TITLE
Get number of total minted NFTS so farr

### ISSUE THREAD

**Issue by AleksaMarjanov** [AleksaMarjanov/nft_collection#1]
Getting error for total minted NFTS: 
TypeError: connectedContract.getTotalMinted is not a function
    at getTotalNFTsMintedSoFar (App.jsx:189:51)
    at checkIfWalletIsConnected (App.jsx:54:7)

**Comment by AleksaMarjanov** [comment]
added method in MyEpicNFT.sol to get total of minted nfts & redeployed contract
